### ISSUE TITLE
Add Gamemaker studio 2 and 3

### ISSUE THREAD

**Issue by liangforstudy** [JENOVAAbsolute/128-Bit-Bay-Software#1]
Add Gamemaker studio 2 and 3
Construct 3
Clickteam fusion
Grammarly
Minecraft story mode Android. Apk

**Comment by JENOVAAbsolute** [comment]
> Add Gamemaker studio 2 and 3 Construct 3 Clickteam fusion Grammarly Minecraft story mode Android. Apk

1.) I will not be adding that for safety and privacy reasons. It has a key logger.
2.) I do not add games to my repo unless it has no official source, is a fan game, etc. 
3.) I got zero results for Clickteam Fusion and Construct 3 from my trusted sources. 
4.) I was only able to find Game Maker Studio 2. I will add that for you and comment when it's up.

If you have requests, join our Discord server and ping me in the software channel there instead. Thank you.

**Comment by JENOVAAbsolute** [comment]
GameMaker Studio Ultimate 2 v2022.3.0.624 is added.
